include ../../vep_0/share/make_common.mk
# 2d hybrid: CC+raster sink (DMA-out via tile_emit). 
# no DMA/JPEG input here - libfifo (system lib) is auto-linked by make_tile.mk.
USER_LIBS :=
USER_CFLAGS :=
USER_LINK_FLAGS :=
include ../../vep_0/share/make_tile.mk
