include ../../vep_0/share/make_common.mk

LIBNAME := myfifo
SOURCES := $(wildcard libsrc/*.[cS])
CFLAGS  += -I../../vep_0/libbsp/include -I../../vep_0/libdma-riscv/include

include ../../vep_0/share/make_library.mk
