include ../../vep_0/share/make_common.mk
# 2c function-parallel: FIFO smoke-test consumer (iqzz+idct+cc). Pure compute,
# no DMA/JPEG input here - libfifo (system lib) is auto-linked by make_tile.mk.
USER_LIBS :=
USER_CFLAGS :=
USER_LINK_FLAGS :=
include ../../vep_0/share/make_tile.mk
